### ISSUE TITLE
./a11ym requires 2+ urls to work

### ISSUE THREAD

**Issue by louiscremen** [liip/TheA11yMachine#66]
Hey guys, weird bug:

If I use the command
` ./a11ym http://example.org`

Then I receive this:

```
 <localpath>/TheA11yMachine/node_modules/simplecrawler/lib/crawler.js:50
         throw new Error("The crawler needs a URL string to know where to start crawling");
         ^
 
 Error: The crawler needs a URL string to know where to start crawling
     at new Crawler (<localpath>/TheA11yMachine/node_modules/simplecrawler/lib/crawler.js:50:15)
     at Object.<anonymous> (<localpath>/TheA11yMachine/lib/crawler.js:43:26)
     at Module._compile (module.js:409:26)
     at Object.Module._extensions..js (module.js:416:10)
     at Module.load (module.js:343:32)
     at Function.Module._load (module.js:300:12)
     at Module.require (module.js:353:17)
     at require (internal/module.js:12:17)
     at Object.<anonymous> (<localpath>/TheA11yMachine/a11ym:224:19)
     at Module._compile (module.js:409:26)
```

But if I use two urls (even if they are the same):
`./a11ym http://example.org http://example.org`

Then it works fine.

Any ideas?

**Comment by Manest** [comment]
Same problem here 
in package.json, we have a 
"simplecrawler": "git+https://github.com/cgiffard/node-simplecrawler.git#master"

But node-simplecrawler 1.0.0 release last month (https://github.com/cgiffard/node-simplecrawler/releases/tag/v1.0.0) and one of the breaking change is :

> The crawler is now initiated with a single argument - initialURL. The crawler will infer the host property as well as initialPort and initialPath from this single URL.

**Comment by reipaul** [comment]
ditto with can't use one url
