### ISSUE TITLE
when running a11ym  -s HTML  on windows machine an error occurs

### ISSUE THREAD

**Issue by stevefaulkner** [liip/TheA11yMachine#99]
error:
```
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at ChildProcess.<anonymous> (C:\Users\faulk\AppData\Roaming\npm\node_modules\the-a11y-machine\lib\tester.js:180:30)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

any help with this would be appreciated!

**Comment by stevefaulkner** [comment]
fixed it:
added 
`'-Xss512k',`
before` '-jar',` https://github.com/liip/TheA11yMachine/blob/master/lib/tester.js#L160

**Comment by Hywan** [comment]
Do we need to patch it?
